In [1]:
pip install gspread

Looking in indexes: https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/python/simple, https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/pypi-mirror/simple
Requirement already satisfied: gspread in /opt/conda/lib/python3.7/site-packages (5.1.1)
Requirement already satisfied: google-auth>=1.12.0 in /opt/conda/lib/python3.7/site-packages (from gspread) (2.6.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /opt/conda/lib/python3.7/site-packages (from gspread) (0.4.6)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (1.16.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (4.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (0.2.7)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.0)
Requirement already satisfied: requests>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.0.11)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install analytics-utility-core

Looking in indexes: https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/python/simple, https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/pypi-mirror/simple
Requirement already satisfied: analytics-utility-core in /opt/conda/lib/python3.7/site-packages (0.0.140)
Requirement already satisfied: wf-config>=0.2.0 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (1.0.1)
Requirement already satisfied: fasteners in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (0.17.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (2.27.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (3.0.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (59.8.0)
Requirement already satisfied: wf-secrets>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (1.1.0)
Requirement already satisfied: analytics-enums in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (0.1.36)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (2.8.2)
Requirement already satisfied: typing-extensions<4.0,>=3.7.4.1 in /opt/conda/lib/python3.7/site-packages (from wf-config>=0.2.0->analytics-utility-core) (3.10.0.2)
Requirement already satisfied: pyaes~=1.6 in /opt/conda/lib/python3.7/site-packages (from wf-secrets>=0.7.0->analytics-utility-core) (1.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.7/site-packages (from jinja2->analytics-utility-core) (2.0.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil->analytics-utility-core) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (1.26.8)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from datetime import datetime
import pandas as pd
from analytics_cloud_core import Clients, ClientType

In [4]:
from analytics_utility_core import secret_store
secret_store.add_cred('bi-gsuite-automation', r'''{"token": "ya29.ImDAB8WR81zQtjIdks8zDQxpY0Hxq4hExeLxs6C_fK7_g_N9BCGIIzeTFWbiB9IJawIhWU3dIWF7_pZulJcno67y2oIEJ6hFP0DDAHg1ze7iahAohEgf6gN0rHdkrF5mlZ4", "refresh_token": "1//0dvn8xSl9FBdHCgYIARAAGA0SNwF-L9IrYPdycsVFTNIRaOz6NCYFjS4IZvcbNrJ8IU1HlN38AFAZ60RKY0CxrPEBITyhL85SQqc", "id_token": null, "scopes": ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/spreadsheets.readonly"], "token_uri": "https://accounts.google.com/o/oauth2/token", "client_id": "370667759854-sk5pij71cci5insi3ctmcr4rgbo6kov0.apps.googleusercontent.com", "client_secret": "7oF5TU3DBsv5YnRLYizTjto0", "quota_project_id": null}''')

In [5]:
#Defining credentials
service = Clients.get_client(ClientType.SHEETS, name="bi-gsuite-automation")

In [6]:
# this will return a gspread client
gc = Clients.get_client(ClientType.GSPREAD, name="bi-gsuite-automation")

In [7]:
sheetid='1i-LwDJlpgipVf-lRUvNRgAGOqj7XBxucE2rUu09pAGs'
tab_schedule ='Carrier Schedule'
tab_capacity ='Capacity'
tab_pendingreport = 'Pending Report'
tab_allocation_origin_ops = 'Pending Report - Allocation Result'

In [8]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_allocation_origin_ops).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_allocation_originops = pd.DataFrame(values, columns=header)

In [9]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_pendingreport).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_pendingreport = pd.DataFrame(values, columns=header)

In [10]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_schedule).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_schedule = pd.DataFrame(values, columns=header)

In [11]:
df_schedule

,ServiceString,Week,Carrier,Contract,Service,Vessel,Voyage,Origin,ETD,Destination,Delivery,ETA,TransitTime
0,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
1,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
2,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
3,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
4,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USDAL,6/10/2023,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19904,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,CNYTN,10/10/2023,USLAX,USHOU,11/11/2023,32
19905,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USLAX,10/27/2023,15
19906,HLCUQFPPN2,41,HLCU,QFP,PN2,NAVIOS UNISON,016E,CNYTN,10/12/2023,USTIW,USCVG,11/5/2023,24
19907,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USDAL,11/11/2023,30
19908,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USHOU,11/11/2023,30

In [12]:
df_transit=df_schedule

In [13]:
df_transit

,ServiceString,Week,Carrier,Contract,Service,Vessel,Voyage,Origin,ETD,Destination,Delivery,ETA,TransitTime
0,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
1,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
2,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
3,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
4,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USDAL,6/10/2023,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19904,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,CNYTN,10/10/2023,USLAX,USHOU,11/11/2023,32
19905,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USLAX,10/27/2023,15
19906,HLCUQFPPN2,41,HLCU,QFP,PN2,NAVIOS UNISON,016E,CNYTN,10/12/2023,USTIW,USCVG,11/5/2023,24
19907,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USDAL,11/11/2023,30
19908,HLCUQFPPS4,41,HLCU,QFP,PS4,YM UNIFORM,232E,TWKHH,10/12/2023,USLAX,USHOU,11/11/2023,30

In [14]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_capacity).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_capacity = pd.DataFrame(values, columns=header)

In [15]:
df_capacity

,ServiceString,Carrier,Contract,Service,Vessel,Voyage,Allocation,Booked,Hold,Capacity,Assigned,ETD Week,Week
0,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI 513,E087,22,,0,22,,-,None
1,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A07,E005,22,13,0,9,,Week32,32
2,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A08,E005,22,9,0,13,,Week33,33
3,HLCUCVAAA7,HLCU,CVA,AA7,ATHOS,028E,22,15,0,7,,Week34,34
4,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI 625,E009,22,7,0,15,,Week35,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,MAEUREGEU,MAEU,REG,EU,Week38,,100,0,0,100,3,Week38,38
210,MAEUREGEU,MAEU,REG,EU,Week39,,100,0,0,100,,Week39,39
211,MAEUREGEU,MAEU,REG,EU,Week40,,100,0,0,100,,Week40,40
212,MAEUREGEU,MAEU,REG,EU,Week41,,100,0,0,100,,Week41,41
213,MAEUREGEU,MAEU,REG,EU,Week42,,100,0,0,100,,Week42,42

In [16]:
import pandas as pd
import pandas_gbq

In [17]:
pandas_gbq.to_gbq(df_capacity, 'csn_reporting_isc.tbl_aas_capacity', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7681.88it/s]

In [18]:
pandas_gbq.to_gbq(df_transit, 'csn_reporting_isc.tbl_aas_transit', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7612.17it/s]

In [19]:
pandas_gbq.to_gbq(df_schedule, 'csn_reporting_isc.tbl_aas_schedule', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8719.97it/s]

In [20]:
pandas_gbq.to_gbq(df_pendingreport, 'csn_reporting_isc.tbl_pendingreport', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 3894.43it/s]

In [21]:
pandas_gbq.to_gbq(df_allocation_originops, 'csn_reporting_isc.tbl_originops_allocation', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7796.10it/s]

In [22]:
sheetid='1UYv_ZLVcqVUiV_biMoubk8tAAC1yriDQ_ORF2cLOdmg'
port_mapping='Port Mapping'

In [23]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=port_mapping).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_portmapping = pd.DataFrame(values, columns=header)

In [24]:
df_portmapping

             Port Port_Code
0         Toronto     CATOR
1          Fuzhou     CNFZG
2          Ningbo     CNNBG
3          Nansha     CNNSA
4         Qingdao     CNQDG
..            ...       ...
62  Prince Rupert     CAYPR
63      Vancouver     CAVAN
64        Antwerp     BEANR
65        Seattle     USSEA
66        Halifax     CAHAL

[67 rows x 2 columns]

In [25]:
pandas_gbq.to_gbq(df_portmapping, 'csn_reporting_isc.tbl_aas_portmapping', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7231.56it/s]

In [26]:
from analytics_db_core import EasyQuery, CONFIGURED_LOCALES
CONFIGURED_LOCALES.configure_for_user(integrated_auth=False, basic_auth =False, cloud=True)

In [27]:
query = """
SELECT buy.Origin,
buy.Destination,
buy.Container_Size,
originport.Port_Code AS Origin_Port,
destinationport.Port_Code AS Destination_Port,
CASE 
WHEN buy.Carrier='Hapag-Lloyd' THEN 'HLCU'
WHEN buy.Carrier='CMA' THEN 'CMDU'
WHEN buy.Carrier='Maersk' THEN 'MAEU'
ELSE buy.Carrier
END AS Carrier_Name,
CASE 
WHEN Notes LIKE 'Bunker Included%' THEN Freight_Rate
ELSE Freight_Rate+Bunker_Rate 
END AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_isc_pricing_ocean_buy_rates` buy
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` originport ON buy.Origin=originport.Port
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` destinationport ON buy.Destination=destinationport.Port
WHERE Container_Size NOT IN ('20DRY','45HDRY','20HDRY')
AND (Oc_Effective_Date<= CURRENT_DATE() OR Oc_Effective_Date IS NULL)
AND (Oc_Expiry_Date >=CURRENT_DATE() OR Oc_Expiry_Date IS NULL)
GROUP BY 1,2,3,4,5,6,7
"""

In [28]:
ocean_rate = EasyQuery(cmd=query, target='eden-gbq-ops-prod').get_dataframe()

In [29]:
display(ocean_rate)

,origin,destination,container_size,origin_port,destination_port,carrier_name,rate
0,Nhava Sheva,New York,40DRY,None,USNYC,CMDU,2800.0
1,Nhava Sheva,Norfolk,40DRY,None,USORF,CMDU,2800.0
2,Nhava Sheva,Charleston,40DRY,None,USCHS,CMDU,2800.0
3,Nhava Sheva,Savannah,40DRY,None,USSAV,CMDU,2800.0
4,Mundra,New York,40DRY,None,USNYC,CMDU,2800.0
...,...,...,...,...,...,...,...
8055,Singapore,Southampton,40DRY,SGSIN,GBSOU,HLCU,1874.0
8056,Laem Chabang,Antwerp,40DRY,THLCH,BEANR,HLCU,1874.0
8057,Laem Chabang,Hamburg,40DRY,THLCH,DEHAM,HLCU,1874.0
8058,Laem Chabang,London Gateway Port,40DRY,THLCH,GBLGP,HLCU,1874.0
8059,Laem Chabang,Rotterdam,40DRY,THLCH,NLRTM,HLCU,1874.0

In [30]:
pandas_gbq.to_gbq(ocean_rate, 'csn_reporting_isc.tbl_aas_ocean_rates', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 6636.56it/s]

In [31]:
query2 = """
SELECT schedule.*,
capacity.Allocation AS allocated_capacity,
capacity.Capacity AS available_capacity,
buy.rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_schedule` schedule 
INNER JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_capacity` capacity ON CAST(schedule.ServiceString AS STRING)=CAST(capacity.ServiceString AS STRING) AND schedule.Week=capacity.Week
INNER JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_rates` buy ON schedule.Origin=buy.origin_port AND schedule.Destination=buy.Destination_Port AND schedule.Carrier=buy.carrier_name
"""

In [32]:
aas_combined = EasyQuery(cmd=query2, target='eden-gbq-ops-prod').get_dataframe()

In [33]:
display(aas_combined)

,servicestring,week,carrier,contract,service,vessel,voyage,origin,etd,destination,delivery,eta,transittime,allocated_capacity,available_capacity,rate
0,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNFZG,8/30/2023,USCHS,USCHS,10/8/2023,39,200,135,2529.0
1,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNFZG,8/30/2023,USCHS,USCHS,10/8/2023,39,200,135,2529.0
2,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,9/3/2023,USCHS,USCHS,10/8/2023,35,200,135,2309.0
3,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,9/3/2023,USCHS,USCHS,10/8/2023,35,200,135,2309.0
4,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,9/3/2023,USSAV,USSAV,10/10/2023,37,200,135,2309.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17314,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,VNVUT,9/18/2023,USORF,USORF,10/26/2023,38,60,60,2800.0
17315,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,9/21/2023,USNYC,USNYC,10/23/2023,32,60,60,2850.0
17316,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,9/21/2023,USNYC,USNYC,10/23/2023,32,60,60,2850.0
17317,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,9/21/2023,USORF,USORF,10/26/2023,35,60,60,2800.0
17318,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,9/21/2023,USORF,USORF,10/26/2023,35,60,60,2800.0

In [34]:
pandas_gbq.to_gbq(aas_combined, 'csn_reporting_isc.tbl_aas_combined_table', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8388.61it/s]

In [35]:
data=aas_combined

In [36]:
df_pendingreport

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,Container Type
0,42,VNSGN,WHS-326-31024792,NVO,"LIFESTYLE SOLUTIONS INC.,","KHIET HOA FURNITURE CO., LTD",10/18/2023,USLAX,40,HC
1,44,CNYTN,WHS-36253-31829216,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,11/3/2023,USNYC,40,HQ
2,44,CNYTN,WHS-36253-31829219,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,11/3/2023,USLAX,40,HQ
3,44,CNYTN,WHS-36253-31829218,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,11/3/2023,USJAX,40,HQ
4,44,CNYTN,WHS-36253-31829221,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,11/3/2023,USSAV,40,HQ
...,...,...,...,...,...,...,...,...,...,...
149,35,IDBLW,345294,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,9/2/2023,GBSOU,40,HC
150,35,IDBLW,345295,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,9/2/2023,GBSOU,40,HC
151,33,IDBLW,345301,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,8/19/2023,GBSOU,40,HC
152,34,IDBLW,345303,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,8/26/2023,GBSOU,40,HC
153,35,IDBLW,345297,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,9/2/2023,GBSOU,40,HC

In [37]:
from datetime import timedelta

In [38]:
#specifying priority of carrier
from pandas.api.types import CategoricalDtype
data['carrier'] = data['carrier'].astype(pd.CategoricalDtype(
                  ['HLCU','CMDU','MAEU'], ordered=True))

In [39]:
#removing duplicates
data.drop_duplicates(inplace=True)

In [40]:
#replacing all occurences of VNVUT with VNSGN as they are interchangeable
data['origin'] = data['origin'].str.replace('VNVUT', 'VNSGN')
data['destination'] = data['destination'].str.replace('VNVUT', 'VNSGN')
df_pendingreport['Origin'] = df_pendingreport['Origin'].str.replace('VNVUT', 'VNSGN')
df_pendingreport['Destination'] = df_pendingreport['Destination'].str.replace('VNVUT', 'VNSGN')

In [41]:
df_pendingreport['ECRD']=pd.to_datetime(df_pendingreport['ECRD'])
data['etd']=pd.to_datetime(data['etd'])
data['eta']=pd.to_datetime(data['eta'])

In [42]:
#converting dates to correct format
date1 = pd.to_datetime(data['eta'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
date2 = pd.to_datetime(data['eta'], errors='coerce', format='%m/%d/%Y')
data['eta'] = date1.fillna(date2)
data['eta']=pd.to_datetime(data['eta'])

In [43]:
date1 = pd.to_datetime(data['etd'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
date2 = pd.to_datetime(data['etd'], errors='coerce', format='%m/%d/%Y')
data['etd'] = date1.fillna(date2)
data['etd']=pd.to_datetime(data['etd'])

In [44]:
data['available_capacity']=pd.to_numeric(data['available_capacity'])
data['allocated_capacity']=pd.to_numeric(data['allocated_capacity'])

In [45]:
data

,servicestring,week,carrier,contract,service,vessel,voyage,origin,etd,destination,delivery,eta,transittime,allocated_capacity,available_capacity,rate
0,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNFZG,2023-08-30,USCHS,USCHS,2023-10-08,39,200,135.0,2529.0
2,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,2023-09-03,USCHS,USCHS,2023-10-08,35,200,135.0,2309.0
4,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,2023-09-03,USSAV,USSAV,2023-10-10,37,200,135.0,2309.0
6,MAEUREGUSEC,35,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNQDG,2023-09-03,USORF,USORF,2023-10-13,40,200,135.0,2309.0
8,MAEUREGUSEC,36,MAEU,REG,USEC,ZIM MOUNT RAINER,001E,CNNBG,2023-09-06,USCHS,USCHS,2023-10-08,32,200,172.0,2639.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17309,CMDUREGUS,37,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,CNYTN,2023-09-14,USORF,USORF,2023-10-26,42,60,60.0,2800.0
17311,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,VNSGN,2023-09-18,USNYC,USNYC,2023-10-23,35,60,60.0,2850.0
17313,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,VNSGN,2023-09-18,USORF,USORF,2023-10-26,38,60,60.0,2800.0
17315,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,2023-09-21,USNYC,USNYC,2023-10-23,32,60,60.0,2850.0
17317,CMDUREGUS,38,CMDU,REG,US,CMA CGM PRIDE,1TU46S1MA,SGSIN,2023-09-21,USORF,USORF,2023-10-26,35,60,60.0,2800.0

In [46]:
cols=df_pendingreport.columns
cols

Index(['Week', 'Origin', 'Shipment', 'Service Level', 'Supplier', 'Shipper',
       'ECRD', 'Destination', 'Container Size', 'Container Type'],
      dtype='object')

In [47]:
# initializing dataframe which holds final result
fin=pd.DataFrame()

In [48]:
data.dtypes

servicestring                 object
week                          object
carrier                     category
contract                      object
service                       object
vessel                        object
voyage                        object
origin                        object
etd                   datetime64[ns]
destination                   object
delivery                      object
eta                   datetime64[ns]
transittime                   object
allocated_capacity             int64
available_capacity           float64
rate                         float64
dtype: object

In [49]:
df_pendingreport.dtypes

Week                      object
Origin                    object
Shipment                  object
Service Level             object
Supplier                  object
Shipper                   object
ECRD              datetime64[ns]
Destination               object
Container Size            object
Container Type            object
dtype: object

In [50]:
for ind in range(len(df_pendingreport)):
  orig=df_pendingreport.loc[ind,'Origin'] #origin in pending report
  dest=df_pendingreport.loc[ind,'Destination'] #destination in pending report
  ecrd=df_pendingreport.loc[ind,'ECRD'] #ECRD in pending report
  min_etd=ecrd+timedelta(days=5)#min time buffer
  max_etd=ecrd+timedelta(days=20)#max time buffer
  df1=data[(data.origin==orig) & (data.destination==dest) & (data.etd>=min_etd) & (data.etd<=max_etd) & (data.available_capacity>0)]# filtering rows which satisfy conditions
  df1.reset_index(inplace=True,drop=True)
  df1.sort_values(by=['carrier','available_capacity'],ascending=[True,False],inplace=True)#sorting first by type of carrier then by decreasing capacity
  df1.reset_index(inplace=True,drop=True)
  df1['rank_cap'] = df1.index + 1 #rank acc to capacity
  df1.sort_values(['rate','carrier'],inplace=True)#sorting first by cost then by type of carrier
  df1.reset_index(inplace=True,drop=True)
  df1['rank_cost'] = df1.index + 1 #rank acc to cost
  df1.sort_values(['eta','carrier'],ascending=[True,True],inplace=True)#sorting first by eta then by type of carrier
  df1.reset_index(inplace=True,drop=True)
  df1['rank_time'] = df1.index + 1 #rank acc to time of arrival
  s=df_pendingreport.loc[[ind],cols]#the current row of pending report as a dataframe
  df2=s.merge(df1, how='outer',left_on='Origin',right_on='origin')#joining current row with all service string allocations with the required ranks
  fin=pd.concat([fin,df2],ignore_index=True)#adding them to final dataset

/opt/conda/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [51]:
fin

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,Container Type,...,destination,delivery,eta,transittime,allocated_capacity,available_capacity,rate,rank_cap,rank_cost,rank_time
0,42,VNSGN,WHS-326-31024792,NVO,"LIFESTYLE SOLUTIONS INC.,","KHIET HOA FURNITURE CO., LTD",2023-10-18,USLAX,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44,CNYTN,WHS-36253-31829216,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-11-03,USNYC,40,HQ,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44,CNYTN,WHS-36253-31829219,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-11-03,USLAX,40,HQ,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44,CNYTN,WHS-36253-31829218,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-11-03,USJAX,40,HQ,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,CNYTN,WHS-36253-31829221,NVO,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-11-03,USSAV,40,HQ,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,35,IDBLW,345294,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,2023-09-02,GBSOU,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,35,IDBLW,345295,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,2023-09-02,GBSOU,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,33,IDBLW,345301,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,2023-08-19,GBSOU,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,34,IDBLW,345303,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,2023-08-26,GBSOU,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,35,IDBLW,345297,OND,XL JOINERY LIMITED,PT SUMATERA TIMBERINDO INDUSTRY,2023-09-02,GBSOU,40,HC,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
fin.dtypes

Week                          object
Origin                        object
Shipment                      object
Service Level                 object
Supplier                      object
Shipper                       object
ECRD                  datetime64[ns]
Destination                   object
Container Size                object
Container Type                object
servicestring                 object
week                          object
carrier                     category
contract                      object
service                       object
vessel                        object
voyage                        object
origin                        object
etd                   datetime64[ns]
destination                   object
delivery                      object
eta                   datetime64[ns]
transittime                   object
allocated_capacity           float64
available_capacity           float64
rate                         float64
rank_cap                     float64
rank_cost                    float64
rank_time                    float64
dtype: object

In [53]:
fin.rename(columns= {'week':'Allocated_Week', 'origin':'Allocated_Origin', 'destination':'Allocated_Destination'}, inplace=True)
fin['rank_cap']=fin['rank_cap'].fillna(0)
fin['rank_cost']=fin['rank_cost'].fillna(0)
fin['rank_time']=fin['rank_time'].fillna(0)
fin['rank_cap']=fin['rank_cap'].astype(int)
fin['rank_cost']=fin['rank_cost'].astype(int)
fin['rank_time']=fin['rank_time'].astype(int)

In [54]:
try:
 pandas_gbq.to_gbq(fin, 'csn_reporting_isc.tbl_aas_allocation_output', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')
except Exception as e:
    print(e)

100%|██████████| 1/1 [00:00<00:00, 7530.17it/s]

In [55]:
query3 = """
SELECT aas.*,
originops.Carrier AS OO_Carrier,
originops.Service AS OO_Service,
originops.Contract AS OO_Contract,
originops.Allocation AS OO_Allocation,
originops.ETD AS OO_ETD,
originops.ETA AS OO_ETA,
originops.Transit AS OO_Transit,
originops.Cost AS OO_Cost
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_allocation_output` aas
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_originops_allocation` originops ON aas.Shipment=originops.SPO
"""

In [56]:
allocation_originops_combined = EasyQuery(cmd=query3, target='eden-gbq-ops-prod').get_dataframe()

In [57]:
allocation_originops_combined

,week,origin,shipment,service level,supplier,shipper,ecrd,destination,container size,container type,...,rank_cost,rank_time,oo_carrier,oo_service,oo_contract,oo_allocation,oo_etd,oo_eta,oo_transit,oo_cost
0,38,MYPGU,WHS-19314-32627140,None,BELLA ESPRIT,DAWN SHIPPING (M) SDN BHD,2023-09-20 00:00:00+00:00,USSAV,None,None,...,1,1,None,None,None,None,None,None,None,None
1,34,IDSUB,WHS-171-32536613,None,MODUS FURNITURE INTERNATIONAL,PT GALANGCITRAMITRA MAJUMAPAN,2023-08-24 00:00:00+00:00,USSAV,None,None,...,2,1,HLCU,EC4,CVA,YM WIDTH,8/30/2023,10/7/2023,38,3100
2,34,IDSUB,WHS-171-32536613,None,MODUS FURNITURE INTERNATIONAL,PT GALANGCITRAMITRA MAJUMAPAN,2023-08-24 00:00:00+00:00,USSAV,None,None,...,1,2,HLCU,EC4,CVA,YM WIDTH,8/30/2023,10/7/2023,38,3100
3,37,CNYTN,WHS-36253-33027616,None,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-09-15 00:00:00+00:00,USCVG,None,None,...,1,7,HLCU,PN2,QFP,YM TOTALITY,9/21/2023,10/5/2023,24,4140
4,37,CNYTN,WHS-36253-33027616,None,HUDSON&CANAL CORP,MODERN HOME FURNITURE CO LTD,2023-09-15 00:00:00+00:00,USCVG,None,None,...,3,8,HLCU,PN2,QFP,YM TOTALITY,9/21/2023,10/5/2023,24,4140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,31,THLCH,WHS-83026-33363395,None,MLILY USA INC,"NISCO (THAILAND) CO., LTD",2023-08-05 00:00:00+00:00,USSAV,None,None,...,7,8,MAEU,USEC,REG,Week33,8/14/2023,9/26/2023,43,2258
706,31,THLCH,WHS-83026-33363405,None,MLILY USA INC,"NISCO (THAILAND) CO., LTD",2023-08-05 00:00:00+00:00,USSAV,None,None,...,7,8,MAEU,USEC,REG,Week33,8/14/2023,9/26/2023,43,2258
707,32,VNSGN,WHS-49575-33278520,None,Sterling Rivers Inc.,SHUOJIA ENTERPRISE LIMITED,2023-08-10 00:00:00+00:00,USSAV,None,None,...,22,17,HLCU,EC4,QFP,NEW YORK EXPRESS,8/23/2023,9/23/2023,31,3000
708,33,VNSGN,WHS-49575-33278533,None,Sterling Rivers Inc.,SHUOJIA ENTERPRISE LIMITED,2023-08-15 00:00:00+00:00,USSAV,None,None,...,26,16,HLCU,EC4,QFP,NEW YORK EXPRESS,8/23/2023,9/23/2023,31,3000
709,33,CNXMG,351738,None,YAHEE TECHNOLOGIES CORP.,SHENZHEN QIANHAI YAHEE E-COMMERCE CO,2023-08-17 00:00:00+00:00,USSAV,None,None,...,15,7,HLCU,EC4,QFP,AIN SNAN EXPRESS,8/23/2023,10/1/2023,39,2800

In [58]:
pandas_gbq.to_gbq(allocation_originops_combined, 'csn_reporting_isc.tbl_aas_allocation_output_combined', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 5966.29it/s]