In [1]:
pip install gspread

Looking in indexes: https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/python/simple, https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/pypi-mirror/simple
Requirement already satisfied: gspread in /opt/conda/lib/python3.7/site-packages (5.1.1)
Requirement already satisfied: google-auth>=1.12.0 in /opt/conda/lib/python3.7/site-packages (from gspread) (2.6.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /opt/conda/lib/python3.7/site-packages (from gspread) (0.4.6)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (0.2.7)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread) (4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.0)
Requirement already satisfied: requests>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.0.11)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install analytics-utility-core

Looking in indexes: https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/python/simple, https://artifactory-haproxy.service.intradsm1.consul.csnzoo.com:8099/artifactory/api/pypi/pypi-mirror/simple
Requirement already satisfied: analytics-utility-core in /opt/conda/lib/python3.7/site-packages (0.0.140)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (59.8.0)
Requirement already satisfied: wf-config>=0.2.0 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (1.0.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (2.27.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (3.0.3)
Requirement already satisfied: analytics-enums in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (0.1.36)
Requirement already satisfied: wf-secrets>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (1.1.0)
Requirement already satisfied: fasteners in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (0.17.3)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.7/site-packages (from analytics-utility-core) (2.8.2)
Requirement already satisfied: typing-extensions<4.0,>=3.7.4.1 in /opt/conda/lib/python3.7/site-packages (from wf-config>=0.2.0->analytics-utility-core) (3.10.0.2)
Requirement already satisfied: pyaes~=1.6 in /opt/conda/lib/python3.7/site-packages (from wf-secrets>=0.7.0->analytics-utility-core) (1.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.7/site-packages (from jinja2->analytics-utility-core) (2.0.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil->analytics-utility-core) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->analytics-utility-core) (1.26.8)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from datetime import datetime
import pandas as pd
from analytics_cloud_core import Clients, ClientType

In [4]:
from analytics_utility_core import secret_store
secret_store.add_cred('bi-gsuite-automation', r'''{"token": "ya29.ImDAB8WR81zQtjIdks8zDQxpY0Hxq4hExeLxs6C_fK7_g_N9BCGIIzeTFWbiB9IJawIhWU3dIWF7_pZulJcno67y2oIEJ6hFP0DDAHg1ze7iahAohEgf6gN0rHdkrF5mlZ4", "refresh_token": "1//0dvn8xSl9FBdHCgYIARAAGA0SNwF-L9IrYPdycsVFTNIRaOz6NCYFjS4IZvcbNrJ8IU1HlN38AFAZ60RKY0CxrPEBITyhL85SQqc", "id_token": null, "scopes": ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/spreadsheets.readonly"], "token_uri": "https://accounts.google.com/o/oauth2/token", "client_id": "370667759854-sk5pij71cci5insi3ctmcr4rgbo6kov0.apps.googleusercontent.com", "client_secret": "7oF5TU3DBsv5YnRLYizTjto0", "quota_project_id": null}''')

In [5]:
#Defining credentials
service = Clients.get_client(ClientType.SHEETS, name="bi-gsuite-automation")

In [6]:
# this will return a gspread client
gc = Clients.get_client(ClientType.GSPREAD, name="bi-gsuite-automation")

In [7]:
# Importing input data from Google Sheets
sheetid='1i-LwDJlpgipVf-lRUvNRgAGOqj7XBxucE2rUu09pAGs'
tab_schedule ='Carrier Schedule'
tab_capacity ='Capacity'
tab_pendingreport = 'Pending Report'
tab_allocation_origin_ops = 'Pending Report - Allocation Result'

In [8]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_allocation_origin_ops).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_allocation_originops = pd.DataFrame(values, columns=header)

In [9]:
#Actual Allocations made by Origin Operations Team
df_allocation_originops

,WK,POL,SPO,Service Level,Supplier,Shipper,ECRD,POD,Container Size,Factory SO Submission Date,...,ETD,Destination,ETA,Delivery,ETAA,Pref,Leadtime,Transit,Cost,InsertDate
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USLAX,40,7/27/2023,...,11/8/2023,USLAX,12/5/2023,USLAX,12/5/2023,2,9,27,1728,10/24/2023
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,7/27/2023,...,11/10/2023,USEWR,12/12/2023,USEWR,12/12/2023,4,11,32,2288,10/24/2023
2,44,VNSGN,WHS-37382-33234038,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,7/27/2023,...,11/10/2023,USEWR,12/12/2023,USEWR,12/12/2023,4,11,32,2288,10/24/2023
3,44,VNSGN,WHS-37382-33234044,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USJAX,40,7/27/2023,...,11/8/2023,USJAX,12/26/2023,USJAX,12/26/2023,2,9,48,2288,10/24/2023
4,43,CNYTN,351061,OND,TUTTI FRUTTI DIRECT LTD,TUTTI BAMBINI XIAMEN TRADING CO LTD,10/27/2023,GBFXT,40,8/12/2023,...,11/5/2023,GBFXT,12/3/2023,GBFXT,12/3/2023,1,9,28,900,10/24/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,45,CNQDG,WHS-58673-34181896,NVO,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,11/10/2023,USSAV,40,10/19/2023,...,11/20/2023,USSAV,12/21/2023,USSAV,12/21/2023,1,10,31,2800,10/24/2023
64,45,CNSHG,WHS-118-33363921,NVO,DOREL HOME FURNISHINGS IN,LUCKY BELL TRADING LIMITED,11/11/2023,USNYC,40,10/19/2023,...,11/17/2023,USNYC,12/18/2023,USNYC,12/18/2023,1,6,31,2800,10/24/2023
65,46,CNSHG,WHS-58673-34440702,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/19/2023,...,11/24/2023,USNYC,12/25/2023,USNYC,12/25/2023,1,9,31,2800,10/24/2023
66,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/19/2023,...,11/24/2023,USNYC,12/25/2023,USNYC,12/25/2023,1,9,31,2800,10/24/2023
67,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,11/9/2023,DEHAM,40,10/20/2023,...,11/17/2023,DEHAM,12/21/2023,DEHAM,12/21/2023,1,8,34,900,10/24/2023

In [10]:
#Pulling only the latest allocation record for all the pending report SPOs based on their InsertDate each day
df_allocation_originops['rank_ap'] = df_allocation_originops.groupby('SPO')['InsertDate'].rank(method='first', ascending=False)
df_allocation_originops = df_allocation_originops[df_allocation_originops.rank_ap == 1]
del df_allocation_originops['rank_ap']
df_allocation_originops = df_allocation_originops.reset_index(drop=True)

In [11]:
df_allocation_originops

,WK,POL,SPO,Service Level,Supplier,Shipper,ECRD,POD,Container Size,Factory SO Submission Date,...,ETD,Destination,ETA,Delivery,ETAA,Pref,Leadtime,Transit,Cost,InsertDate
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USLAX,40,7/27/2023,...,11/8/2023,USLAX,12/5/2023,USLAX,12/5/2023,2,9,27,1728,10/24/2023
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,7/27/2023,...,11/10/2023,USEWR,12/12/2023,USEWR,12/12/2023,4,11,32,2288,10/24/2023
2,44,VNSGN,WHS-37382-33234038,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,7/27/2023,...,11/10/2023,USEWR,12/12/2023,USEWR,12/12/2023,4,11,32,2288,10/24/2023
3,44,VNSGN,WHS-37382-33234044,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USJAX,40,7/27/2023,...,11/8/2023,USJAX,12/26/2023,USJAX,12/26/2023,2,9,48,2288,10/24/2023
4,43,CNYTN,351061,OND,TUTTI FRUTTI DIRECT LTD,TUTTI BAMBINI XIAMEN TRADING CO LTD,10/27/2023,GBFXT,40,8/12/2023,...,11/5/2023,GBFXT,12/3/2023,GBFXT,12/3/2023,1,9,28,900,10/24/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,45,CNQDG,WHS-58673-34181896,NVO,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,11/10/2023,USSAV,40,10/19/2023,...,11/20/2023,USSAV,12/21/2023,USSAV,12/21/2023,1,10,31,2800,10/24/2023
64,45,CNSHG,WHS-118-33363921,NVO,DOREL HOME FURNISHINGS IN,LUCKY BELL TRADING LIMITED,11/11/2023,USNYC,40,10/19/2023,...,11/17/2023,USNYC,12/18/2023,USNYC,12/18/2023,1,6,31,2800,10/24/2023
65,46,CNSHG,WHS-58673-34440702,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/19/2023,...,11/24/2023,USNYC,12/25/2023,USNYC,12/25/2023,1,9,31,2800,10/24/2023
66,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/19/2023,...,11/24/2023,USNYC,12/25/2023,USNYC,12/25/2023,1,9,31,2800,10/24/2023
67,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,11/9/2023,DEHAM,40,10/20/2023,...,11/17/2023,DEHAM,12/21/2023,DEHAM,12/21/2023,1,8,34,900,10/24/2023

In [12]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_pendingreport).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_pendingreport = pd.DataFrame(values, columns=header)

In [13]:
df_pendingreport

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,InsertDate
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USLAX,40,10/24/2023
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
2,44,VNSGN,WHS-37382-33234038,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
3,44,VNSGN,WHS-37382-33234044,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USJAX,40,10/24/2023
4,43,CNYTN,351061,OND,TUTTI FRUTTI DIRECT LTD,TUTTI BAMBINI XIAMEN TRADING CO LTD,10/27/2023,GBFXT,40,10/24/2023
...,...,...,...,...,...,...,...,...,...,...
63,45,CNQDG,WHS-58673-34181896,NVO,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,11/10/2023,USSAV,40,10/24/2023
64,45,CNSHG,WHS-118-33363921,NVO,DOREL HOME FURNISHINGS IN,LUCKY BELL TRADING LIMITED,11/11/2023,USNYC,40,10/24/2023
65,46,CNSHG,WHS-58673-34440702,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
66,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
67,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,11/9/2023,DEHAM,40,10/24/2023

In [14]:
#Pulling only the latest shipment from the pending report based on the Insert Date
df_pendingreport['rank_ap'] = df_pendingreport.groupby('Shipment')['InsertDate'].rank(method='first', ascending=False)
df_pendingreport = df_pendingreport[df_pendingreport.rank_ap == 1]
del df_pendingreport['rank_ap']
df_pendingreport = df_pendingreport.reset_index(drop=True)

In [15]:
df_pendingreport

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,InsertDate
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USLAX,40,10/24/2023
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
2,44,VNSGN,WHS-37382-33234038,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
3,44,VNSGN,WHS-37382-33234044,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USJAX,40,10/24/2023
4,43,CNYTN,351061,OND,TUTTI FRUTTI DIRECT LTD,TUTTI BAMBINI XIAMEN TRADING CO LTD,10/27/2023,GBFXT,40,10/24/2023
...,...,...,...,...,...,...,...,...,...,...
63,45,CNQDG,WHS-58673-34181896,NVO,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,11/10/2023,USSAV,40,10/24/2023
64,45,CNSHG,WHS-118-33363921,NVO,DOREL HOME FURNISHINGS IN,LUCKY BELL TRADING LIMITED,11/11/2023,USNYC,40,10/24/2023
65,46,CNSHG,WHS-58673-34440702,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
66,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
67,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,11/9/2023,DEHAM,40,10/24/2023

In [16]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_schedule).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_schedule = pd.DataFrame(values, columns=header)

In [17]:
# Carrier Schedule being pulled from Input Data
df_schedule

,ServiceString,Week,Carrier,Contract,Service,Vessel,Voyage,Origin,ETD,Destination,Delivery,ETA,TransitTime
0,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
1,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USLAX,5/26/2023,14
2,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
3,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USOAK,USOAK,5/31/2023,19
4,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,5/12/2023,USLAX,USDAL,6/10/2023,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19522,HLCUQFPPN4,51,HLCU,QFP,PN4,YM TRILLION,008E,CNSHG,12/24/2023,USTIW,USCVG,1/19/2024,26
19523,HLCUQFPPS7,51,HLCU,QFP,PS7,YM WELLNESS,037E,CNYTN,12/24/2023,USLAX,USDAL,1/23/2024,30
19524,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,12/25/2023,CAVAN,CAVAN,1/8/2024,14
19525,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,12/25/2023,CAVAN,CATOR,1/20/2024,26
19526,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,12/25/2023,CAVAN,USCHI,1/21/2024,27

In [18]:
#converting dates to correct format
df1 = pd.to_datetime(df_schedule['ETA'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
df2 = pd.to_datetime(df_schedule['ETA'], errors='coerce', format='%m/%d/%Y')
df_schedule['ETA'] = df1.fillna(df2)
df_schedule['ETA']=pd.to_datetime(df_schedule['ETA'])

In [19]:
#converting dates to correct format
df1 = pd.to_datetime(df_schedule['ETD'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
df2 = pd.to_datetime(df_schedule['ETD'], errors='coerce', format='%m/%d/%Y')
df_schedule['ETD'] = df1.fillna(df2)
df_schedule['ETD']=pd.to_datetime(df_schedule['ETD'])

In [20]:
df_transit=df_schedule

In [21]:
# Schedules being copied as they have the transit data information
df_transit

,ServiceString,Week,Carrier,Contract,Service,Vessel,Voyage,Origin,ETD,Destination,Delivery,ETA,TransitTime
0,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,2023-05-12,USLAX,USLAX,2023-05-26,14
1,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,2023-05-12,USLAX,USLAX,2023-05-26,14
2,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,2023-05-12,USOAK,USOAK,2023-05-31,19
3,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,2023-05-12,USOAK,USOAK,2023-05-31,19
4,HLCUQFPPS3,19,HLCU,QFP,PS3,SEASPAN ADONIS,070E,CNYTN,2023-05-12,USLAX,USDAL,2023-06-10,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19522,HLCUQFPPN4,51,HLCU,QFP,PN4,YM TRILLION,008E,CNSHG,2023-12-24,USTIW,USCVG,2024-01-19,26
19523,HLCUQFPPS7,51,HLCU,QFP,PS7,YM WELLNESS,037E,CNYTN,2023-12-24,USLAX,USDAL,2024-01-23,30
19524,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,2023-12-25,CAVAN,CAVAN,2024-01-08,14
19525,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,2023-12-25,CAVAN,CATOR,2024-01-20,26
19526,HLCUQFPPN2,52,HLCU,QFP,PN2,NAVIOS UNISON,017E,CNSHG,2023-12-25,CAVAN,USCHI,2024-01-21,27

In [22]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=tab_capacity).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_capacity = pd.DataFrame(values, columns=header)

In [23]:
# Available capacity being the input from the Origin Operations
df_capacity

,ServiceString,Carrier,Contract,Service,Vessel,Voyage,Allocation,Booked,Hold,Capacity,Assigned,ETD Week,Week,InsertDate
0,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A05,E001,33,0,0,33,,Week42,42,10/24/2023
1,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A10,E003,33,0,0,33,,Week43,43,10/24/2023
2,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A07,E006,33,0,0,33,,Week44,44,10/24/2023
3,HLCUCVAAA7,HLCU,CVA,AA7,NORFOLK EXPRESS,001E,33,1,0,32,,Week45,45,10/24/2023
4,HLCUCVAAA7,HLCU,CVA,AA7,WAN HAI A08,007E,33,0,0,33,,Week46,46,10/24/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,,CMDU,REG,EU,202347,,60,0,0,60,2,Week47,47,10/24/2023
200,,CMDU,REG,EU,202348,,60,0,0,60,,Week48,48,10/24/2023
201,,CMDU,REG,EU,202349,,60,0,0,60,,Week49,49,10/24/2023
202,,CMDU,REG,EU,202350,,60,0,0,60,,Week50,50,10/24/2023
203,,CMDU,REG,EU,202351,,60,0,0,60,,Week51,51,10/24/2023

In [24]:
import pandas as pd
import pandas_gbq

In [25]:
pandas_gbq.to_gbq(df_capacity, 'csn_reporting_isc.tbl_aas_capacity', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8050.49it/s]

In [26]:
pandas_gbq.to_gbq(df_transit, 'csn_reporting_isc.tbl_aas_transit', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7073.03it/s]

In [27]:
pandas_gbq.to_gbq(df_schedule, 'csn_reporting_isc.tbl_aas_schedule', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8630.26it/s]

In [28]:
pandas_gbq.to_gbq(df_pendingreport, 'csn_reporting_isc.tbl_pendingreport', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 9962.72it/s]

In [29]:
pandas_gbq.to_gbq(df_allocation_originops, 'csn_reporting_isc.tbl_originops_allocation', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 11522.81it/s]

In [30]:
sheetid='1UYv_ZLVcqVUiV_biMoubk8tAAC1yriDQ_ORF2cLOdmg'
port_mapping='Port Mapping'
supplier_mapping ='SupplierMapping_Extract'

In [31]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=port_mapping).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_portmapping = pd.DataFrame(values, columns=header)

In [32]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=supplier_mapping).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_suppliermapping = pd.DataFrame(values, columns=header)

In [33]:
df_portmapping

                       Port Port_Code
0                 Zhongshan     AQZGN
1                   Antwerp     BEANR
2                     Muara     BNMUA
3                   Halifax     CAHAL
4                   Toronto     CATOR
..                      ...       ...
208        Ho Chi Minh City     VNSGN
209                 Quinhon     VNUIH
210                Qui Nhon     VNUIH
211                Vung Tau     VNVUT
212  Vung Tau (Ho Chi Minh)     VNVUT

[213 rows x 2 columns]

In [34]:
df_suppliermapping

     SupplierID                    SupplierName
0          1384  TWIN STAR HOME (CLASSIC FLAME)
1         16936    Best Sign International Inc.
2          6890                       ACG Green
3          6064                 UKBirlea-Parent
4         17229                         Astella
...         ...                             ...
1291      50303                  MassivMoebel24
1292      65588         OSC International, Inc.
1293       5735                HOME BAZAAR INC.
1294      74817                    Wecasual Inc
1295      19440               Home Weavers Inc.

[1296 rows x 2 columns]

In [35]:
pandas_gbq.to_gbq(df_portmapping, 'csn_reporting_isc.tbl_aas_portmapping', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 6689.48it/s]

In [36]:
pandas_gbq.to_gbq(df_suppliermapping, 'csn_reporting_isc.tbl_aas_suppliermapping', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8338.58it/s]

In [37]:
# Automating CVA Buy Rate which is being stored in a Google Sheet
sheetid='1i-LwDJlpgipVf-lRUvNRgAGOqj7XBxucE2rUu09pAGs'
cva_contracts ='CVA'

In [38]:
result = service.spreadsheets().values().get(spreadsheetId=sheetid, range=cva_contracts).execute()
header = result.get('values', [])[0]  # If the first line has column names, else just read without [0]
values = result.get('values', [])[1:]  # Everything else is data.

# Convert data to dataframe, you can use the read data as per your requirement.
df_cva_contracts = pd.DataFrame(values, columns=header)

In [39]:
pandas_gbq.to_gbq(df_cva_contracts, 'csn_reporting_isc.tbl_cva_contract', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 12052.60it/s]

In [40]:
from analytics_db_core import EasyQuery, CONFIGURED_LOCALES
CONFIGURED_LOCALES.configure_for_user(integrated_auth=False, basic_auth =False, cloud=True)

In [41]:
latestcontract = """
WITH T1 AS (SELECT *,
ROW_NUMBER() OVER(PARTITION BY Origin_Code, Destination_Code, Carrier, Loading, Discharge ORDER BY CAST(Contract_Expiry AS DATE) DESC,CAST(Oc_Effective_Date AS DATE) DESC ) as rm
FROM (SELECT *,
CASE WHEN Oc_Expiry_Date IS NULL THEN '2027-08-01'
ELSE Oc_Expiry_Date
END AS Contract_Expiry
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_isc_pricing_ocean_buy_rates`)
WHERE Container_Size='40DRY')

SELECT *
FROM T1
WHERE rm=1
"""

In [42]:
qfp_latestrate = EasyQuery(cmd=latestcontract, target='eden-gbq-ops-prod').get_dataframe()

In [43]:
pandas_gbq.to_gbq(qfp_latestrate, 'csn_reporting_isc.tbl_aas_latestcontract', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7516.67it/s]

In [44]:
# Query to combine QFP & CVA contract buy rates and fetching only the latest contracts
query = """
SELECT Origin,
Loading,
Discharge,
Destination,
CASE 
WHEN Carrier='Hapag-Lloyd' THEN 'HLCU'
WHEN Carrier='CMA' THEN 'CMDU'
WHEN Carrier='Maersk' THEN 'MAEU'
ELSE Carrier
END AS Carrier_Name,
CAST(Container_Size AS STRING) AS Container_Size,
'QFP' AS Contract_Type,
CASE 
WHEN Notes LIKE 'Bunker Included%' THEN Freight_Rate
ELSE Freight_Rate+Bunker_Rate 
END AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_latestcontract`
GROUP BY 1,2,3,4,5,6,7,8

UNION ALL

SELECT Origin,
Loading,
Discharge,
Destination,
CASE 
WHEN Carrier='Hapag-Lloyd' THEN 'HLCU'
WHEN Carrier='CMA' THEN 'CMDU'
WHEN Carrier='Maersk' THEN 'MAEU'
ELSE Carrier
END AS Carrier_Name,
Container_Size,
'CVA' AS Contract_Type,
CAST(All_In AS INT) AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_cva_contract`
WHERE Container_Size NOT IN ('20DRY','45HDRY','20HDRY','40HDRY')
AND Freight_Rate IS NOT NULL
AND (SAFE_CAST(Oc_Effective_Date AS DATE)<= CURRENT_DATE() OR SAFE_CAST(Oc_Effective_Date AS DATE) IS NULL)
AND (SAFE_CAST(Oc_Expiry_Date AS DATE) >=CURRENT_DATE() OR SAFE_CAST(Oc_Expiry_Date AS DATE) IS NULL)
GROUP BY 1,2,3,4,5,6,7,8
"""

In [45]:
ocean_buy_rate = EasyQuery(cmd=query, target='eden-gbq-ops-prod').get_dataframe()

In [46]:
display(ocean_buy_rate)

,origin,loading,discharge,destination,carrier_name,container_size,contract_type,rate
0,Ningbo,Ningbo,Oakland,Oakland,HLCU,40DRY,CVA,2000
1,Ningbo,Ningbo,Tacoma,Tacoma,HLCU,40DRY,CVA,2000
2,Ningbo,Ningbo,Tacoma,Seattle,HLCU,40DRY,CVA,2000
3,Ningbo,Ningbo,Seattle,Tacoma,HLCU,40DRY,CVA,2000
4,Ningbo,Ningbo,Seattle,Seattle,HLCU,40DRY,CVA,2000
...,...,...,...,...,...,...,...,...
14593,Jawaharlal Nehru,Jawaharlal Nehru,Baltimore,Aberdeen,MAEU,40DRY,QFP,3437
14594,Jawaharlal Nehru,Jawaharlal Nehru,Los Angeles,Romeoville,MAEU,40DRY,QFP,5227
14595,Jawaharlal Nehru,Jawaharlal Nehru,Newark,Romeoville,MAEU,40DRY,QFP,5427
14596,Jawaharlal Nehru,Jawaharlal Nehru,Savannah,Mcdonough,MAEU,40DRY,QFP,4407
14597,Jawaharlal Nehru,Jawaharlal Nehru,Norfolk,Romeoville,MAEU,40DRY,QFP,5427

In [47]:
pandas_gbq.to_gbq(ocean_buy_rate, 'csn_reporting_isc.tbl_aas_ocean_buy_rates', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 12710.01it/s]

In [48]:
#Mapping port codes with the ocean buy rate
query2 = """
SELECT buy.Origin,
buy.Destination,
buy.Container_Size,
originport.Port_Code AS Origin_Port,
destinationport.Port_Code AS Destination_Port,
loading.Port_Code AS Loading_Port,
discharge.Port_Code AS Discharge_Port,
buy.Carrier_Name,
buy.contract_type,
buy.rate AS Original_Rate,
CASE 
WHEN buy.carrier_name='HLCU' AND buy.Contract_Type='QFP' THEN buy.rate-1000
WHEN buy.carrier_name='HLCU' AND buy.Contract_Type='CVA' THEN buy.rate-500
ELSE buy.rate
END AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_buy_rates` buy
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` originport ON buy.Origin=originport.Port
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` destinationport ON buy.Destination=destinationport.Port
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` loading ON buy.Loading=loading.Port
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_portmapping` discharge ON buy.Discharge=discharge.Port
GROUP BY 1,2,3,4,5,6,7,8,9,10,11

"""

In [49]:
ocean_rate = EasyQuery(cmd=query2, target='eden-gbq-ops-prod').get_dataframe()

In [50]:
display(ocean_rate)

,origin,destination,container_size,origin_port,destination_port,loading_port,discharge_port,carrier_name,contract_type,original_rate,rate
0,Wuhu,Cincinnati,40DRY,CNWHI,USCVG,CNWHI,USCVG,MAEU,QFP,4452,4452
1,Wuhu,Perris,40DRY,CNWHI,None,CNWHI,None,MAEU,QFP,2717,2717
2,Wuhu,Chicago,40DRY,CNWHI,USCHI,CNWHI,USCHI,MAEU,QFP,3527,3527
3,Wuhu,Memphis,40DRY,CNWHI,USMEM,CNWHI,USMEM,MAEU,QFP,3967,3967
4,Wuhu,Romeoville,40DRY,CNWHI,None,CNWHI,None,MAEU,QFP,4632,4632
...,...,...,...,...,...,...,...,...,...,...,...
22522,Vung Tau (Ho Chi Minh),Seattle,40DRY,VNVUT,USSEA,VNVUT,USTIW,HLCU,QFP,2000,1000
22523,Vung Tau (Ho Chi Minh),Oakland,40DRY,VNVUT,USOAK,VNVUT,USOAK,HLCU,QFP,2000,1000
22524,Vung Tau (Ho Chi Minh),Tacoma,40DRY,VNVUT,USTIW,VNVUT,USTIW,HLCU,QFP,2000,1000
22525,Vung Tau (Ho Chi Minh),Long Beach,40DRY,VNVUT,USLAX,VNVUT,USLAX,HLCU,QFP,2000,1000
22526,Vung Tau (Ho Chi Minh),Los Angeles,40DRY,VNVUT,USLAX,VNVUT,USLAX,HLCU,QFP,2000,1000

In [51]:
pandas_gbq.to_gbq(ocean_rate, 'csn_reporting_isc.tbl_aas_ocean_rates', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 7767.23it/s]

In [52]:
#Mapping port codes with the ocean buy rate
query = """
SELECT *
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_rates`

UNION ALL

----CMA European Ports
SELECT 
CAST(tb.Origin AS STRING) AS origin,
CAST(ocr.destination AS STRING) as destination, 
CAST(ocr.container_size AS STRING) AS container_size,
CAST(tb.Origin_Code AS STRING) AS origin_port,
ocr.destination_port,
ocr.loading_port,
ocr.discharge_port,
ocr.carrier_name,
ocr.contract_type,
CAST(ocr.Original_Rate AS FLOAT64)+CAST(tb.Rate AS FLOAT64) AS Original_Rate,
CAST(ocr.Original_Rate AS FLOAT64)+CAST(tb.Rate AS FLOAT64) AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_rates` ocr
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_isc_pricing_cma_eu_tariff_book` tb ON ocr.loading_port=tb.Loading_Code
WHERE ocr.destination_port IN ('GBFXT','DEHAM','CATOR','DEBRV','FRLEH','GBLGP','GBLIV','GBSOU','NLRTM') AND ocr.carrier_name='CMDU' AND tb.Container_Size='40DRY'


UNION ALL

----Hapag CVA Trans-shipments
SELECT 
CAST(tb.Origin AS STRING) AS origin,
CAST(ocr.destination AS STRING) as destination, 
CAST(ocr.container_size AS STRING) AS container_size,
CAST(tb.Origin_Code AS STRING) AS origin_port,
ocr.destination_port,
ocr.loading_port,
ocr.discharge_port,
ocr.carrier_name,
ocr.contract_type,
CAST(ocr.Original_Rate AS FLOAT64)+CAST(tb.Rate AS FLOAT64) AS Original_Rate,
CAST(ocr.Original_Rate AS FLOAT64)+CAST(tb.Rate AS FLOAT64) AS Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_rates` ocr
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_isc_pricing_cma_eu_tariff_book` tb ON ocr.loading_port=tb.Loading_Code
WHERE ocr.carrier_name='HLCU' AND tb.Container_Size='40DRY' AND ocr.Contract_Type='CVA'
"""

In [53]:
ocean_final_rate = EasyQuery(cmd=query, target='eden-gbq-ops-prod').get_dataframe()

In [54]:
display(ocean_final_rate)

,origin,destination,container_size,origin_port,destination_port,loading_port,discharge_port,carrier_name,contract_type,original_rate,rate
0,Wuhu,Cincinnati,40DRY,CNWHI,USCVG,CNWHI,USCVG,MAEU,QFP,4452,4452
1,Wuhu,Perris,40DRY,CNWHI,None,CNWHI,None,MAEU,QFP,2717,2717
2,Wuhu,Chicago,40DRY,CNWHI,USCHI,CNWHI,USCHI,MAEU,QFP,3527,3527
3,Wuhu,Memphis,40DRY,CNWHI,USMEM,CNWHI,USMEM,MAEU,QFP,3967,3967
4,Wuhu,Romeoville,40DRY,CNWHI,None,CNWHI,None,MAEU,QFP,4632,4632
...,...,...,...,...,...,...,...,...,...,...,...
22522,Vung Tau (Ho Chi Minh),Seattle,40DRY,VNVUT,USSEA,VNVUT,USTIW,HLCU,QFP,2000,1000
22523,Vung Tau (Ho Chi Minh),Oakland,40DRY,VNVUT,USOAK,VNVUT,USOAK,HLCU,QFP,2000,1000
22524,Vung Tau (Ho Chi Minh),Tacoma,40DRY,VNVUT,USTIW,VNVUT,USTIW,HLCU,QFP,2000,1000
22525,Vung Tau (Ho Chi Minh),Long Beach,40DRY,VNVUT,USLAX,VNVUT,USLAX,HLCU,QFP,2000,1000
22526,Vung Tau (Ho Chi Minh),Los Angeles,40DRY,VNVUT,USLAX,VNVUT,USLAX,HLCU,QFP,2000,1000

In [55]:
pandas_gbq.to_gbq(ocean_final_rate, 'csn_reporting_isc.tbl_aas_ocean_final_rate', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 11096.04it/s]

In [56]:
# Creating a combined input tables based on schedule, capacity and buy rates
query3 = """
WITH Hapag_Capacity AS (
SELECT *
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_capacity`
WHERE Carrier='HLCU'
),

NonHapag AS (
SELECT *
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_capacity`
WHERE Carrier!='HLCU'
)

SELECT schedule.*,
buy.loading_port AS Loading_Port,
buy.discharge_port AS Discharge_Port,
COALESCE(NH.Allocation,HL.Allocation) AS allocated_capacity,
COALESCE(NH.Capacity,HL.capacity) AS available_capacity,
COALESCE(NH.Booked,HL.Booked) AS booked_capacity,
COALESCE(NH.InsertDate,HL.InsertDate) AS InsertDate,
COALESCE(NH.Week,HL.Week) AS Cap_Week,
buy.Rate,
buy.Original_Rate
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_schedule` schedule 
LEFT JOIN NonHapag NH ON CAST(schedule.ServiceString AS STRING)=CAST(NH.ServiceString AS STRING) AND schedule.Week=NH.Week
LEFT JOIN Hapag_Capacity HL ON CAST(schedule.ServiceString AS STRING)=CAST(HL.ServiceString AS STRING) AND CAST(schedule.Vessel AS STRING)=CAST(HL.Vessel AS STRING) AND CAST(schedule.Voyage AS STRING)=CAST(HL.Voyage AS STRING)
INNER JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_final_rate` buy ON schedule.Origin=buy.origin_port AND schedule.Carrier=buy.carrier_name AND schedule.Delivery=buy.destination_port
"""

In [57]:
aas_combined = EasyQuery(cmd=query3, target='eden-gbq-ops-prod').get_dataframe()

In [58]:
display(aas_combined)

,servicestring,week,carrier,contract,service,vessel,voyage,origin,etd,destination,...,transittime,loading_port,discharge_port,allocated_capacity,available_capacity,booked_capacity,insertdate,cap_week,rate,original_rate
0,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24 00:00:00+00:00,NLRTM,...,33,CNQDG,NLRTM,None,None,None,None,None,900,900
1,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24 00:00:00+00:00,NLRTM,...,33,CNQIN,NLRTM,None,None,None,None,None,900,900
2,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24 00:00:00+00:00,NLRTM,...,33,CNTAO,NLRTM,None,None,None,None,None,900,900
3,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24 00:00:00+00:00,GBFXT,...,37,CNQDG,GBFXT,None,None,None,None,None,900,900
4,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24 00:00:00+00:00,GBFXT,...,37,CNQIN,GBFXT,None,None,None,None,None,900,900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67118,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04 00:00:00+00:00,USLAX,...,40,IDSRG,USLAX,None,None,None,None,None,1728,1728
67119,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04 00:00:00+00:00,CAVAN,...,43,IDSRG,CAVAN,None,None,None,None,None,1728,1728
67120,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04 00:00:00+00:00,USOAK,...,60,IDSRG,USOAK,None,None,None,None,None,1728,1728
67121,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04 00:00:00+00:00,USFWT,...,65,IDSRG,USLAX,None,None,None,None,None,3738,3738
67122,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04 00:00:00+00:00,USFWT,...,71,IDSRG,USLAX,None,None,None,None,None,3738,3738

In [59]:
pandas_gbq.to_gbq(aas_combined, 'csn_reporting_isc.tbl_aas_combined_input', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 8594.89it/s]

In [60]:
data=aas_combined

In [61]:
data.dtypes

servicestring                      object
week                               object
carrier                            object
contract                           object
service                            object
vessel                             object
voyage                             object
origin                             object
etd                   datetime64[ns, UTC]
destination                        object
delivery                           object
eta                   datetime64[ns, UTC]
transittime                        object
loading_port                       object
discharge_port                     object
allocated_capacity                 object
available_capacity                 object
booked_capacity                    object
insertdate                         object
cap_week                           object
rate                                int64
original_rate                       int64
dtype: object

In [62]:
df_pendingreport

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,InsertDate
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USLAX,40,10/24/2023
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
2,44,VNSGN,WHS-37382-33234038,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USNYC,40,10/24/2023
3,44,VNSGN,WHS-37382-33234044,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,10/30/2023,USJAX,40,10/24/2023
4,43,CNYTN,351061,OND,TUTTI FRUTTI DIRECT LTD,TUTTI BAMBINI XIAMEN TRADING CO LTD,10/27/2023,GBFXT,40,10/24/2023
...,...,...,...,...,...,...,...,...,...,...
63,45,CNQDG,WHS-58673-34181896,NVO,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,11/10/2023,USSAV,40,10/24/2023
64,45,CNSHG,WHS-118-33363921,NVO,DOREL HOME FURNISHINGS IN,LUCKY BELL TRADING LIMITED,11/11/2023,USNYC,40,10/24/2023
65,46,CNSHG,WHS-58673-34440702,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
66,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,11/15/2023,USNYC,40,10/24/2023
67,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,11/9/2023,DEHAM,40,10/24/2023

In [63]:
from datetime import timedelta

In [64]:
#specifying priority of carrier
from pandas.api.types import CategoricalDtype
data['carrier'] = data['carrier'].astype(pd.CategoricalDtype(
                  ['HLCU','CMDU','MAEU'], ordered=True))

In [65]:
#removing duplicates
data.drop_duplicates(inplace=True)

In [66]:
#replacing all occurences of VNVUT with VNSGN as they are interchangeable
data['origin'] = data['origin'].str.replace('VNVUT', 'VNSGN')
data['delivery'] = data['delivery'].str.replace('VNVUT', 'VNSGN')
df_pendingreport['Origin'] = df_pendingreport['Origin'].str.replace('VNVUT', 'VNSGN')
df_pendingreport['Destination'] = df_pendingreport['Destination'].str.replace('VNVUT', 'VNSGN')
df_pendingreport['Destination'] = df_pendingreport['Destination'].str.replace('USLGB', 'USLAX')

In [67]:
df_pendingreport['ECRD']=pd.to_datetime(df_pendingreport['ECRD'])
data['etd']=pd.to_datetime(data['etd'])
data['eta']=pd.to_datetime(data['eta'])

In [68]:
#converting dates to correct format
#date1 = pd.to_datetime(data['eta'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
#date2 = pd.to_datetime(data['eta'], errors='coerce', format='%m/%d/%Y')
#data['eta'] = date1.fillna(date2)
#data['eta']=pd.to_datetime(data['eta'])

In [69]:
#date1 = pd.to_datetime(data['etd'], errors='coerce', format='%Y-%d-%m %H:%M:%S').astype('datetime64[D]')
#date2 = pd.to_datetime(data['etd'], errors='coerce', format='%m/%d/%Y')
#data['etd'] = date1.fillna(date2)
data['etd']=pd.to_datetime(data['etd']).dt.tz_localize(None)
data['eta']=pd.to_datetime(data['eta']).dt.tz_localize(None)

In [70]:
data.dtypes

servicestring                 object
week                          object
carrier                     category
contract                      object
service                       object
vessel                        object
voyage                        object
origin                        object
etd                   datetime64[ns]
destination                   object
delivery                      object
eta                   datetime64[ns]
transittime                   object
loading_port                  object
discharge_port                object
allocated_capacity            object
available_capacity            object
booked_capacity               object
insertdate                    object
cap_week                      object
rate                           int64
original_rate                  int64
dtype: object

In [71]:
data['available_capacity']=pd.to_numeric(data['available_capacity'])
data['allocated_capacity']=pd.to_numeric(data['allocated_capacity'])
data['booked_capacity']=pd.to_numeric(data['booked_capacity'])

In [72]:
data.reset_index(inplace=True,drop=True)
data['new_index']=data.index

In [73]:
data

,servicestring,week,carrier,contract,service,vessel,voyage,origin,etd,destination,...,loading_port,discharge_port,allocated_capacity,available_capacity,booked_capacity,insertdate,cap_week,rate,original_rate,new_index
0,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24,NLRTM,...,CNQDG,NLRTM,NaN,NaN,NaN,None,None,900,900,0
1,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24,NLRTM,...,CNQIN,NLRTM,NaN,NaN,NaN,None,None,900,900,1
2,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24,NLRTM,...,CNTAO,NLRTM,NaN,NaN,NaN,None,None,900,900,2
3,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24,GBFXT,...,CNQDG,GBFXT,NaN,NaN,NaN,None,None,900,900,3
4,CMDUREGEU,47,CMDU,REG,EU,FAL6/EVER ALP,0LAG9W1MA,CNQDG,2023-11-24,GBFXT,...,CNQIN,GBFXT,NaN,NaN,NaN,None,None,900,900,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44233,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04,USLAX,...,IDSRG,USLAX,NaN,NaN,NaN,None,None,1728,1728,44233
44234,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04,CAVAN,...,IDSRG,CAVAN,NaN,NaN,NaN,None,None,1728,1728,44234
44235,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04,USOAK,...,IDSRG,USOAK,NaN,NaN,NaN,None,None,1728,1728,44235
44236,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04,USFWT,...,IDSRG,USLAX,NaN,NaN,NaN,None,None,3738,3738,44236
44237,MAEUREGUSWC,49,MAEU,REG,USWC,ZHONG AN XIN HUA Y,348N,IDSRG,2023-12-04,USFWT,...,IDSRG,USLAX,NaN,NaN,NaN,None,None,3738,3738,44237

In [74]:
cols=df_pendingreport.columns
cols

Index(['Week', 'Origin', 'Shipment', 'Service Level', 'Supplier', 'Shipper',
       'ECRD', 'Destination', 'Container Size', 'InsertDate'],
      dtype='object')

In [75]:
# initializing dataframe which holds final result
fin=pd.DataFrame()

In [76]:
data.dtypes

servicestring                 object
week                          object
carrier                     category
contract                      object
service                       object
vessel                        object
voyage                        object
origin                        object
etd                   datetime64[ns]
destination                   object
delivery                      object
eta                   datetime64[ns]
transittime                   object
loading_port                  object
discharge_port                object
allocated_capacity           float64
available_capacity           float64
booked_capacity              float64
insertdate                    object
cap_week                      object
rate                           int64
original_rate                  int64
new_index                      int64
dtype: object

In [77]:
import warnings
warnings.filterwarnings("ignore")

In [78]:
df_pendingreport.dtypes

Week                      object
Origin                    object
Shipment                  object
Service Level             object
Supplier                  object
Shipper                   object
ECRD              datetime64[ns]
Destination               object
Container Size            object
InsertDate                object
dtype: object

In [79]:
#for ind in range(len(df_pendingreport)):
 # orig=df_pendingreport.loc[ind,'Origin'] #origin in pending report
  #dest=df_pendingreport.loc[ind,'Destination'] #destination in pending report
  #ecrd=df_pendingreport.loc[ind,'ECRD'] #ECRD in pending report
  #min_etd=ecrd+timedelta(days=5)#min time buffer
  #max_etd=ecrd+timedelta(days=14)
  
   # df1=data[(data.origin==orig) & (data.delivery==dest) & (data.etd>=min_etd) & (data.etd<=max_etd) & (data.available_capacity>0)]# filtering rows which satisfy conditions
  #df1.reset_index(inplace=True,drop=True)
  #df1["rank_cap"] = df1.sort_values(['carrier','available_capacity'], ascending=[True,False]).groupby(['carrier','available_capacity'], sort=False).ngroup() + 1 #rank acc to capacity
  #df1["rank_cost"] = df1[["rate","carrier"]].apply(tuple,axis=1).rank(method='dense').astype(int)#rank acc to cost
  #df1["rank_time"] = df1[['eta','carrier','transittime']].apply(tuple,axis=1).rank(method='dense').astype(int)#rank acc to time
  #df1["rank_sum"]=df1["rank_cap"]+df1["rank_cost"]+df1["rank_time"]
  #df1.sort_values("rank_sum",inplace=True)
  #s=df_pendingreport.loc[[ind],cols]#the current row of pending report as a dataframe
  #df2=s.merge(df1, how='outer',left_on='Origin',right_on='origin')#joining current row with all service string allocations with the required ranks
  #fin=pd.concat([fin,df2],ignore_index=True)#adding them to final dataset

In [80]:
for ind in range(len(df_pendingreport)):
  orig=df_pendingreport.loc[ind,'Origin'] #origin in pending report
  dest=df_pendingreport.loc[ind,'Destination'] #destination in pending report
  ecrd=df_pendingreport.loc[ind,'ECRD'] #ECRD in pending report
  min_etd=ecrd+timedelta(days=6)#min time buffer
  max_etd=ecrd+timedelta(days=14)
  df1=data[(data.origin==orig) & (data.delivery==dest) & (data.etd>=min_etd) & (data.etd<=max_etd) & (data.available_capacity>0)]# filtering rows which satisfy conditions
  df1.reset_index(inplace=True,drop=True)
  df1['transittime'] = df1['transittime'].astype('int')
  rate_min= df1['rate'].min()
  transit_min=df1['transittime'].min()
  eta_min=df1['eta'].min()
  df1["rank_cost"] = round((1 + (df1['rate'] - rate_min) / rate_min), 3)#rank acc to cost
  df1["rank_time"] = round((1 + (df1['transittime'] - transit_min) / transit_min)/2, 3)#rank acc to time
  df1["rank_eta"]=round((1 + (df1['eta']- eta_min).dt.days/transit_min)/2, 3)
  df1["rank_speed"]=round(df1['rank_time']+df1['rank_eta'],2)
  df1['combined_rank']= round(0.1*(df1['rank_time']+df1['rank_eta'])+0.9*(df1['rank_cost']),3)
  if not df1.empty:
      df1['combined_rank'] = df1.apply(lambda x: x['combined_rank']-0.2 if ((x['service']=='EC2')| (x['service']=='EC5')) else x['combined_rank'], axis=1)#to accomodate EC2 and EC5 (Port Exclusivity)
  df1.sort_values("combined_rank",inplace=True)
  df1.reset_index(inplace=True,drop=True)
  if len(df1)!=0:
    ser=df1.loc[0,'servicestring']
    wk=df1.loc[0,'week']
    df2=data[(data.week==wk) & (data.servicestring==ser)]
    data_ind=df2['new_index']
    df2.available_capacity=df2.available_capacity-1
    df2.booked_capacity=df2.booked_capacity+1
    data.iloc[data_ind]=df2

    df1.loc[(df1['week'] == wk) & (df1.servicestring==ser), 'available_capacity'] -= 1
    df1.loc[(df1['week'] == wk) & (df1.servicestring==ser), 'booked_capacity'] += 1
    # print(data.iloc[data_ind])
  s=df_pendingreport.loc[[ind],cols]#the current row of pending report as a dataframe
  df2=s.merge(df1, how='outer',left_on='Origin',right_on='origin')#joining current row with all service string allocations with the required ranks
  fin=pd.concat([fin,df2],ignore_index=True)#adding them to final dataset

In [81]:
fin

,Week,Origin,Shipment,Service Level,Supplier,Shipper,ECRD,Destination,Container Size,InsertDate,...,insertdate,cap_week,rate,original_rate,new_index,rank_cost,rank_time,rank_eta,rank_speed,combined_rank
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30,USLAX,40,10/24/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30,USNYC,40,10/24/2023,...,10/24/2023,45,2269.0,2269.0,38653.0,1.000,0.500,0.500,1.00,1.000
2,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30,USNYC,40,10/24/2023,...,10/24/2023,45,2269.0,2269.0,38654.0,1.000,0.500,0.500,1.00,1.000
3,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30,USNYC,40,10/24/2023,...,10/24/2023,45,2288.0,2288.0,38655.0,1.008,0.500,0.500,1.00,1.007
4,44,VNSGN,WHS-37382-33234035,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30,USNYC,40,10/24/2023,...,10/24/2023,45,2288.0,2288.0,38656.0,1.008,0.500,0.500,1.00,1.007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,2023-11-15,USNYC,40,10/24/2023,...,10/24/2023,47,2188.0,2188.0,37703.0,1.216,0.500,0.500,1.00,1.194
599,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,2023-11-15,USNYC,40,10/24/2023,...,10/24/2023,47,2500.0,3000.0,17451.0,1.389,0.554,0.554,1.11,1.361
600,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,2023-11-15,USNYC,40,10/24/2023,...,10/24/2023,47,2500.0,3000.0,17453.0,1.389,0.589,0.589,1.18,1.368
601,46,CNSHG,WHS-58673-34440706,NVO,TIANJIN WOSHANG INTL TRAD,JIAXING ANYEE INTELLIGENT FURNITURE,2023-11-15,USNYC,40,10/24/2023,...,10/24/2023,47,2500.0,3000.0,14375.0,1.389,0.714,0.714,1.43,1.393
602,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,2023-11-09,DEHAM,40,10/24/2023,...,10/24/2023,47,996.0,996.0,3541.0,1.000,0.500,0.500,1.00,1.000

In [82]:
fin.dtypes

Week                          object
Origin                        object
Shipment                      object
Service Level                 object
Supplier                      object
Shipper                       object
ECRD                  datetime64[ns]
Destination                   object
Container Size                object
InsertDate                    object
servicestring                 object
week                          object
carrier                     category
contract                      object
service                       object
vessel                        object
voyage                        object
origin                        object
etd                   datetime64[ns]
destination                   object
delivery                      object
eta                   datetime64[ns]
transittime                  float64
loading_port                  object
discharge_port                object
allocated_capacity           float64
available_capacity           float64
booked_capacity              float64
insertdate                    object
cap_week                      object
rate                         float64
original_rate                float64
new_index                    float64
rank_cost                    float64
rank_time                    float64
rank_eta                     float64
rank_speed                   float64
combined_rank                float64
dtype: object

In [83]:
fin.rename(columns= {'week':'Allocated_Week', 'origin':'Allocated_Origin', 'destination':'Allocated_Destination', 'Service Level':'Service_Level', 'insertdate' : 'Insert'}, inplace=True)
fin['rank_time']=fin['rank_time'].fillna(0)
fin['rank_eta']=fin['rank_eta'].fillna(0)
fin['rank_cost']=fin['rank_cost'].fillna(0)
fin['rank_speed']=fin['rank_speed'].fillna(0)
fin['combined_rank']=fin['combined_rank'].fillna(0)

In [84]:
try:
 pandas_gbq.to_gbq(fin, 'csn_reporting_isc.tbl_aas_allocation_output', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')
except Exception as e:
    print(e)

100%|██████████| 1/1 [00:00<00:00, 9341.43it/s]

In [85]:
query5 = """
SELECT aas.*,
CASE
WHEN aas.service_level IN ('NVO','ACN') THEN 'FBCG'
WHEN aas.service_level IN ('OND') THEN 'FBS'
ELSE aas.service_level
END AS servicelevel,
'40HC' AS Container_size,
originops.Carrier AS OO_Carrier,
originops.Service AS OO_Service,
originops.Contract AS OO_Contract,
originops.Allocation AS OO_Allocation,
originops.Remark AS OO_Remark,
originops.ETD AS OO_ETD,
originops.ETA AS OO_ETA,
originops.Transit AS OO_Transit,
originops.Cost AS OO_Cost,
NV.NV_Vessel,
NV.NV_POL,
NV.NV_POD,
NV.Container_Moved,
ROUND(NV.Act_Transit,2) AS Act_Transit,
ROUND(NV.Max_Transit,2) AS Max_Transit,
ROUND(NV.Min_Transit,2) AS Min_Transit
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_allocation_output` aas
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_originops_allocation` originops ON aas.Shipment=originops.SPO
LEFT JOIN (SELECT port_of_loading_code AS NV_POL,
port_of_discharge_code AS NV_POD,
ocean_carrier_name AS NV_Carrier,
main_vessel_name AS NV_Vessel,
COUNT(DISTINCT CONCAT(container_number,MBL)) AS Container_Moved,
AVG(DATE_DIFF(DATE(POD_vessel_ata),DATE(POL_vessel_atd),day)) Act_Transit,
MAX((DATE_DIFF(DATE(POD_vessel_ata),DATE(POL_vessel_atd),day))) Max_Transit,
MIN(DATE_DIFF(DATE(POD_vessel_ata),DATE(POL_vessel_atd),day)) Min_Transit
---ABS(DATE_DIFF(DATE(POD_vessel_ata),DATE(POL_vessel_atd),day) - DATE_DIFF(DATE(POD_vessel_eta),DATE(POL_vessel_etd),day)) abs_daydiff
FROM `wf-gcp-us-ae-cgf-core-prod.core.navios_distinct_shipment`
GROUP BY 
port_of_loading_code ,
port_of_discharge_code,
ocean_carrier_name,
main_vessel_name) NV ON aas.vessel=NV.NV_Vessel AND aas.allocated_origin=NV.NV_POL AND aas.allocated_destination=NV.NV_POD
"""

In [86]:
allocation_originops_combined = EasyQuery(cmd=query5, target='eden-gbq-ops-prod').get_dataframe()

In [87]:
allocation_originops_combined

,week,origin,shipment,service_level,supplier,shipper,ecrd,destination,container size,insertdate,...,oo_eta,oo_transit,oo_cost,nv_vessel,nv_pol,nv_pod,container_moved,act_transit,max_transit,min_transit
0,44,VNSGN,WHS-37382-33234047,NVO,Highbury Furnishing LLC,Royal Furniture production and trading Company...,2023-10-30 00:00:00+00:00,USLAX,None,10/24/2023,...,12/5/2023,27,1728,None,None,None,NaN,NaN,NaN,NaN
1,45,CNTXG,356312,OND,LETTOI LLC,"HUNAN XIAOLUBENBEN E-COMMERCE CO.,LT",2023-11-10 00:00:00+00:00,USLAX,None,10/24/2023,...,12/16/2023,26,1628,None,None,None,NaN,NaN,NaN,NaN
2,43,CNNBG,WHS-58624-34006757,NVO,EBELLO HOME INC,"ZOY HOME FURNISHING CO,LTD",2023-10-23 00:00:00+00:00,USLAX,None,10/24/2023,...,11/18/2023,17,1628,None,None,None,NaN,NaN,NaN,NaN
3,46,CNSHG,355605,OND,SUNWAY EUROPE GMBH,SUNJOY INDUSTRY CO LTD,2023-11-18 00:00:00+00:00,PLGDN,None,10/24/2023,...,1/12/2024,45,996,None,None,None,NaN,NaN,NaN,NaN
4,43,CNSHG,357797,OND,STARPOWER INTERNATIONAL L,NINGBO JIANGBEI JIANGZHONG INDUSTRY,2023-10-25 00:00:00+00:00,USLAX,None,10/24/2023,...,11/18/2023,14,1628,None,None,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,46,CNSHG,355811,OND,Source One Marketing Inc.,"HAINING JIUZHOU FURNITURE CO.,LTD.",2023-11-17 00:00:00+00:00,USORF,None,10/24/2023,...,12/22/2023,29,2800,DORTMUND EXPRESS,CNSHG,USORF,1.0,44.0,44.0,44.0
603,46,CNSHG,355725,OND,Source One Marketing Inc.,"HAINING JIUZHOU FURNITURE CO.,LTD.",2023-11-17 00:00:00+00:00,USORF,None,10/24/2023,...,12/22/2023,29,2800,DORTMUND EXPRESS,CNSHG,USORF,1.0,44.0,44.0,44.0
604,46,CNSHG,355725,OND,Source One Marketing Inc.,"HAINING JIUZHOU FURNITURE CO.,LTD.",2023-11-17 00:00:00+00:00,USORF,None,10/24/2023,...,12/22/2023,29,2800,DORTMUND EXPRESS,CNSHG,USORF,1.0,44.0,44.0,44.0
605,46,CNSHG,355725,OND,Source One Marketing Inc.,"HAINING JIUZHOU FURNITURE CO.,LTD.",2023-11-17 00:00:00+00:00,USORF,None,10/24/2023,...,12/22/2023,29,2800,DORTMUND EXPRESS,CNSHG,USORF,1.0,44.0,44.0,44.0
606,46,CNSHG,355725,OND,Source One Marketing Inc.,"HAINING JIUZHOU FURNITURE CO.,LTD.",2023-11-17 00:00:00+00:00,USORF,None,10/24/2023,...,12/22/2023,29,2800,DORTMUND EXPRESS,CNSHG,USORF,1.0,44.0,44.0,44.0

In [88]:
pandas_gbq.to_gbq(allocation_originops_combined, 'csn_reporting_isc.tbl_aas_allocation_output_combined', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 1710.56it/s]

In [89]:
best_allocation = """
WITH T1 AS (SELECT *,
CONCAT(oo_carrier,oo_contract,oo_service) AS OriginOps_ServiceString,
ROW_NUMBER()
OVER (PARTITION BY Shipment ORDER BY combined_rank ASC) AS rm
FROM `csn_reporting_isc.tbl_aas_allocation_output_combined`)

SELECT *
FROM T1
WHERE rm=1
"""

In [90]:
best_allocation = EasyQuery(cmd=best_allocation, target='eden-gbq-ops-prod').get_dataframe()

In [91]:
pandas_gbq.to_gbq(best_allocation, 'csn_reporting_isc.tbl_aas_allocation_best', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 9686.61it/s]

In [92]:
worst_allocation = """
WITH T1 AS (SELECT *,
ROW_NUMBER()
OVER (PARTITION BY Shipment ORDER BY combined_rank DESC) AS rm
FROM `csn_reporting_isc.tbl_aas_allocation_output_combined`)

SELECT *
FROM T1
WHERE rm=1
"""

In [93]:
worst_allocation = EasyQuery(cmd=worst_allocation, target='eden-gbq-ops-prod').get_dataframe()

In [94]:
worst_allocation

,week,origin,shipment,service_level,supplier,shipper,ecrd,destination,container size,insertdate,...,oo_transit,oo_cost,nv_vessel,nv_pol,nv_pod,container_moved,act_transit,max_transit,min_transit,rm
0,43,CNSHG,353384,OND,"Legacy Commercial Holdings, Inc. DBA Armen Living",ZHEJIANG HUANCHEN CHAIR INDUSTRY CO.,2023-10-25 00:00:00+00:00,USLAX,None,10/24/2023,...,14,1628,None,None,None,NaN,NaN,NaN,NaN,1
1,43,CNXMG,358400,OND,Instadecor ltd,"L & T POTTERY CO.,LTD.",2023-10-25 00:00:00+00:00,GBFXT,None,10/24/2023,...,38,996,MSC NICOLA MASTRO,CNXMG,GBFXT,0.0,NaN,NaN,NaN,1
2,43,CNQDG,351462,OND,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,2023-10-23 00:00:00+00:00,USNYC,None,10/24/2023,...,32,2188,None,None,None,NaN,NaN,NaN,NaN,1
3,43,CNXMG,358399,OND,Instadecor ltd,"L & T POTTERY CO.,LTD.",2023-10-25 00:00:00+00:00,GBFXT,None,10/24/2023,...,38,996,MSC NICOLA MASTRO,CNXMG,GBFXT,0.0,NaN,NaN,NaN,1
4,44,CNQDG,351459,OND,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,2023-10-30 00:00:00+00:00,USNYC,None,10/24/2023,...,32,2188,None,None,None,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,45,CNTXG,356312,OND,LETTOI LLC,"HUNAN XIAOLUBENBEN E-COMMERCE CO.,LT",2023-11-10 00:00:00+00:00,USLAX,None,10/24/2023,...,26,1628,None,None,None,NaN,NaN,NaN,NaN,1
64,46,CNQDG,356088,OND,ASPIRE FURNITURE LTD,MWF INTERNATIONAL,2023-11-15 00:00:00+00:00,GBFXT,None,10/24/2023,...,37,900,MSC DILETTA,CNQDG,GBFXT,3.0,50.67,54.0,45.0,1
65,45,CNYTN,358016,OND,FLATO INTERIOR GMBH,HUIZHOU OLX FURINTURE CO.LTD,2023-11-09 00:00:00+00:00,DEHAM,None,10/24/2023,...,34,900,MAERSK CAMPTON,CNYTN,DEHAM,3.0,33.00,33.0,33.0,1
66,46,CNTXG,WHS-58938-34003995,NVO,LANGFANGSHI LIUTAI JIAJU,LANGFANG LIUTAI FURNITURE CO LTD,2023-11-17 00:00:00+00:00,GBFXT,None,10/24/2023,...,39,900,MADISON MAERSK,CNTXG,GBFXT,3.0,49.00,49.0,49.0,1
67,43,CNQDG,351461,OND,TIANJIN WOSHANG INTL TRAD,CAOXIAN ZHONGZHOU HOUSEHOLD PRODUCTS,2023-10-23 00:00:00+00:00,USNYC,None,10/24/2023,...,32,2188,None,None,None,NaN,NaN,NaN,NaN,1

In [95]:
pandas_gbq.to_gbq(worst_allocation, 'csn_reporting_isc.tbl_aas_allocation_worst', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 11949.58it/s]

In [96]:
performance = """
SELECT best.shipment,
best.origin AS Origin,
best.destination AS Destination,
best.ECRD AS ECRD,
best.etd AS ETD,
best.servicestring AS Allocated_ServiceString,
best.carrier AS Allocated_Carrier,
best.Vessel AS Allocated_Vessel,
best.Voyage AS Allocated_Voyage,
best.oo_carrier AS OriginOps_Carrier,
best.OriginOps_ServiceString AS OriginOps_ServiceString,
best.OO_Remark AS OriginOps_Vessel,
best.Original_Rate AS Allocated_Cost,
best.Rate AS LD_Adjusted_Cost,
best.transittime AS Allocated_Time,
best.oo_cost AS OriginOps_Cost,
best.oo_transit AS OriginOps_Time,
best.eta AS Allocated_ETA,
best.oo_eta AS OriginOps_ETA,
SAFE_CAST(best.oo_cost AS INT64)-SAFE_CAST(best.Rate AS INT64) AS Cost_Difference,
SAFE_CAST(best.oo_transit AS INT64)-SAFE_CAST(best.transittime AS INT64) AS Time_Difference,
AVG(ocrate.original_rate) AS OriginOps_ActualCost,
CASE WHEN best.servicestring!=best.OriginOps_ServiceString THEN "Mismatch Allocation"
ELSE "Matched Allocation"
END AS Allocation_Match
FROM `csn_reporting_isc.tbl_aas_allocation_best` best
LEFT JOIN `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_ocean_rates` ocrate ON best.origin=ocrate.origin_port AND best.destination=ocrate.destination_port AND best.oo_carrier=ocrate.carrier_name
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
"""

In [97]:
performance = EasyQuery(cmd=performance, target='eden-gbq-ops-prod').get_dataframe()

In [98]:
pandas_gbq.to_gbq(performance, 'csn_reporting_isc.tbl_aas_allocation_performance', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 10894.30it/s]

In [99]:
revised_capacity = """
WITH T1 AS (SELECT ServiceString,
Carrier,
Contract,
Service,
allocated_capacity,
MIN(available_capacity) AS available_capacity,
MAX(booked_capacity) AS booked_capacity,
cap_week
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_allocation_output` 
GROUP BY
ServiceString,
Carrier,
Contract,
Service,
allocated_capacity,
--available_capacity,
--booked_capacity,
cap_week

UNION ALL

SELECT 
ServiceString,
Carrier,
Contract,
Service,
CAST(Allocation AS FLOAT64),
CAST(Capacity AS FLOAT64),
CAST(Booked AS FLOAT64),
Week
FROM `wf-gcp-us-ae-ops-prod.csn_reporting_isc.tbl_aas_capacity`)

SELECT 
ServiceString,
Carrier,
Contract,
Service,
allocated_capacity,
MIN(available_capacity) AS Capacity_Available,
MAX(booked_capacity) AS Booked_Capacity,
cap_week
FROM T1
GROUP BY
ServiceString,
Carrier,
Contract,
Service,
allocated_capacity,
--available_capacity,
--booked_capacity,
cap_week
"""

In [100]:
revised_capacity = EasyQuery(cmd=revised_capacity, target='eden-gbq-ops-prod').get_dataframe()

In [101]:
pandas_gbq.to_gbq(revised_capacity, 'csn_reporting_isc.tbl_aas_revised_capacity', project_id = 'wf-gcp-us-ae-ops-prod', if_exists = 'replace')

100%|██████████| 1/1 [00:00<00:00, 12409.18it/s]